# 資料庫連線設定 (記得先在 MySQL 建立一個名為 parkinglot_db 的 Schema)
spring.datasource.url=jdbc:mysql://localhost:3306/parkinglot?serverTimezone=Asia/Taipei
spring.datasource.username=root
spring.datasource.password=root

# JPA/Hibernate 設定
# update 代表：程式啟動時，會自動根據 Entity 類別去更新/建立資料表
spring.jpa.hibernate.ddl-auto=update
# 在控制台印出 SQL 指令 (方便我們除錯)
spring.jpa.show-sql=true